In [1]:
pip install pandas

Requirement already satisfied: pandas in .\miniconda3\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in .\miniconda3\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\miniconda3\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

In [6]:
df=pd.read_csv("C:/Users/ho/Documents/pandas8.csv")
print(df)

   order_id   product     Category    City  Sales  Profit  Quantity        Date
0      1001    Laptop  Electronics  Mumbai  50000    1200         3   1/12/2026
1      1002     Mouse  Electronics   Delhi  41500    1500         4   9/10/2025
2      1003  Keyboard  Electronics    Pune  11000    1100         7   12/2/2026
3      1004   Monitor  Electronics  Mumbai  21800    1400         2  10/10/2026
4      1005      Sofa    Furniture  Nashik   2000    1000         5  12/12/2023
5      1006  Computer  Electronics   Delhi  11100    1200         2   10/9/2026
6      1007       CPU  Electronics  Mumbai  51000    1300         1  11/11/2024
7      1008    Laptop  Electronics    Pune  61005    1800         5   8/10/2026

In [7]:
df.head(5)

   order_id   product     Category    City  Sales  Profit  Quantity        Date
0      1001    Laptop  Electronics  Mumbai  50000    1200         3   1/12/2026
1      1002     Mouse  Electronics   Delhi  41500    1500         4   9/10/2025
2      1003  Keyboard  Electronics    Pune  11000    1100         7   12/2/2026
3      1004   Monitor  Electronics  Mumbai  21800    1400         2  10/10/2026
4      1005      Sofa    Furniture  Nashik   2000    1000         5  12/12/2023

In [8]:
df.tail(4)

   order_id   product     Category    City  Sales  Profit  Quantity        Date
4      1005      Sofa    Furniture  Nashik   2000    1000         5  12/12/2023
5      1006  Computer  Electronics   Delhi  11100    1200         2   10/9/2026
6      1007       CPU  Electronics  Mumbai  51000    1300         1  11/11/2024
7      1008    Laptop  Electronics    Pune  61005    1800         5   8/10/2026

In [9]:
df.describe()

         order_id         Sales       Profit  Quantity
count     8.00000      8.000000     8.000000  8.000000
mean   1004.50000  31175.625000  1312.500000  3.625000
std       2.44949  22338.158486   253.193884  1.995531
min    1001.00000   2000.000000  1000.000000  1.000000
25%    1002.75000  11075.000000  1175.000000  2.000000
50%    1004.50000  31650.000000  1250.000000  3.500000
75%    1006.25000  50250.000000  1425.000000  5.000000
max    1008.00000  61005.000000  1800.000000  7.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  8 non-null      int64
 1   product   8 non-null      str
 2   Category  8 non-null      str
 3   City      8 non-null      str
 4   Sales     8 non-null      int64
 5   Profit    8 non-null      int64
 6   Quantity  8 non-null      int64
 7   Date      8 non-null      str
dtypes: int64(4), str(4)
memory usage: 644.0 bytes

In [14]:
print(df["Sales"].sum())

249405

In [15]:
print(df["Profit"].mean())

1312.5

In [19]:
print(df.groupby("product")["Sales"].sum())

product
CPU          51000
Computer     11100
Keyboard     11000
Laptop      111005
Monitor      21800
Mouse        41500
Sofa          2000
Name: Sales, dtype: int64

In [21]:
print(df.groupby("product")["Sales"].mean())

product
CPU         51000.0
Computer    11100.0
Keyboard    11000.0
Laptop      55502.5
Monitor     21800.0
Mouse       41500.0
Sofa         2000.0
Name: Sales, dtype: float64

In [24]:
print(df.groupby("City")["Sales"].sum().sort_values(ascending=False))

City
Mumbai    122800
Pune       72005
Delhi      52600
Nashik      2000
Name: Sales, dtype: int64

In [25]:
df.isnull()

   order_id  product  Category   City  Sales  Profit  Quantity   Date
0     False    False     False  False  False   False     False  False
1     False    False     False  False  False   False     False  False
2     False    False     False  False  False   False     False  False
3     False    False     False  False  False   False     False  False
4     False    False     False  False  False   False     False  False
5     False    False     False  False  False   False     False  False
6     False    False     False  False  False   False     False  False
7     False    False     False  False  False   False     False  False

In [27]:
df.dropna()

   order_id   product     Category    City  Sales  Profit  Quantity        Date
0      1001    Laptop  Electronics  Mumbai  50000    1200         3   1/12/2026
1      1002     Mouse  Electronics   Delhi  41500    1500         4   9/10/2025
2      1003  Keyboard  Electronics    Pune  11000    1100         7   12/2/2026
3      1004   Monitor  Electronics  Mumbai  21800    1400         2  10/10/2026
4      1005      Sofa    Furniture  Nashik   2000    1000         5  12/12/2023
5      1006  Computer  Electronics   Delhi  11100    1200         2   10/9/2026
6      1007       CPU  Electronics  Mumbai  51000    1300         1  11/11/2024
7      1008    Laptop  Electronics    Pune  61005    1800         5   8/10/2026

In [28]:
df.fillna(0,inplace=False)

   order_id   product     Category    City  Sales  Profit  Quantity        Date
0      1001    Laptop  Electronics  Mumbai  50000    1200         3   1/12/2026
1      1002     Mouse  Electronics   Delhi  41500    1500         4   9/10/2025
2      1003  Keyboard  Electronics    Pune  11000    1100         7   12/2/2026
3      1004   Monitor  Electronics  Mumbai  21800    1400         2  10/10/2026
4      1005      Sofa    Furniture  Nashik   2000    1000         5  12/12/2023
5      1006  Computer  Electronics   Delhi  11100    1200         2   10/9/2026
6      1007       CPU  Electronics  Mumbai  51000    1300         1  11/11/2024
7      1008    Laptop  Electronics    Pune  61005    1800         5   8/10/2026

In [30]:
print(df["Sales"]>25000)

0     True
1     True
2    False
3    False
4    False
5    False
6     True
7     True
Name: Sales, dtype: bool ['Sales']